begin;
create temporary table workflow_users(id uuid, role text);
insert into workflow_users select gen_random_uuid(),role from unnest(array['student','consultant','consultant_lead','admin','reviewer_lead']) role;
insert into auth.users(id) select id from workflow_users;
insert into public.profiles(id,role,name,student_period)
select id,case when role='reviewer_lead' then 'consultant_lead' else role end,'검증 '||role,case when role='student' then '1학년 1학기' end from workflow_users;
create temporary table workflow_data(doc jsonb);
insert into workflow_data values(jsonb_build_object('questionnaireId',gen_random_uuid(),'versionId',gen_random_uuid(),'title','워크플로 검증','sections',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'title','섹션','questions',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'logicalKey',gen_random_uuid(),'text','질문','details',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'title','비공개 의도','text','비공개 설명','visibleToConsultants',false),jsonb_build_object('id',gen_random_uuid(),'title','공개 의도','text','공개 설명','visibleToConsultants',true))))))));
grant select on workflow_users,workflow_data to authenticated;
set local role authenticated;
do $$
declare doc jsonb; vid uuid; owner_id uuid; other_id uuid; consultant_id uuid; rid uuid:=gen_random_uuid(); res jsonb; copied uuid; ar timestamptz; original jsonb; question_doc jsonb;
begin
 select d.doc into doc from workflow_data d; vid:=(doc->>'versionId')::uuid;
 select id into owner_id from workflow_users where role='consultant_lead';
 select id into other_id from workflow_users where role='reviewer_lead';
 select id into consultant_id from workflow_users where role='consultant';
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.save_questionnaire_draft(doc,0,gen_random_uuid());
 perform public.change_questionnaire_status(vid,1,'draft',null,'published',gen_random_uuid());
 if (select revision from public.questionnaire_versions where id=vid)<>2 then raise exception 'Missing revision'; end if;
 begin perform public.change_questionnaire_status(vid,1,'draft',null,'archived',gen_random_uuid()); raise exception 'Stale request accepted'; exception when serialization_failure then null; end;
 perform public.change_questionnaire_status(vid,2,'published',null,'draft',gen_random_uuid());
 if (select published_at from public.questionnaire_versions where id=vid) is not null then raise exception 'Draft timestamp'; end if;
 perform public.change_questionnaire_status(vid,3,'draft',null,'archived',gen_random_uuid());
 select archived_at into ar from public.questionnaires where id=(doc->>'questionnaireId')::uuid;
 if ar is null or not exists(select 1 from public.questionnaire_questions where version_id=vid) then raise exception 'Archive deleted content'; end if;
 begin perform public.change_questionnaire_status(vid,3,'draft',null,'published',gen_random_uuid()); raise exception 'Stale archive accepted'; exception when serialization_failure then null; end;
 perform public.change_questionnaire_status(vid,3,'draft',ar,'draft',gen_random_uuid());
 perform set_config('request.jwt.claim.sub',other_id::text,true);
 begin perform public.change_questionnaire_status(vid,3,'draft',null,'archived',gen_random_uuid()); raise exception 'Nonowner changed'; exception when insufficient_privilege then null; end;
 perform set_config('request.jwt.claim.sub',consultant_id::text,true);
 begin perform public.change_questionnaire_status(vid,3,'draft',null,'distributed',gen_random_uuid()); raise exception 'Consultant changed'; exception when insufficient_privilege then null; end;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.change_questionnaire_status(vid,3,'draft',null,'distributed',gen_random_uuid());
 select to_jsonb(v) into original from public.questionnaire_versions v where id=vid;
 perform set_config('request.jwt.claim.sub',consultant_id::text,true);
 perform public.open_questionnaire_response(vid);
 perform public.save_questionnaire_response(vid,jsonb_build_object(doc#>>'{sections,0,questions,0,id}','보존할 답변'),0,gen_random_uuid(),true);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 res:=public.change_questionnaire_status(vid,4,'distributed',null,'draft',rid); copied:=(res->>'versionId')::uuid;
 if copied=vid or res->>'copied'<>'true' then raise exception 'Copy missing'; end if;
 if public.change_questionnaire_status(vid,4,'distributed',null,'draft',rid)<>res then raise exception 'Retry duplicated copy'; end if;
 if (select to_jsonb(v) from public.questionnaire_versions v where id=vid)<>original then raise exception 'Distributed changed'; end if;
 if not exists(select 1 from public.questionnaire_questions where version_id=copied and logical_key=(doc#>>'{sections,0,questions,0,logicalKey}')::uuid and id<>(doc#>>'{sections,0,questions,0,id}')::uuid) then raise exception 'Copied question identity'; end if;
 if (select count(*) from public.questionnaire_question_details where question_id in(select id from public.questionnaire_questions where version_id=copied))<>2 then raise exception 'Details not copied'; end if;
 if (select status from public.questionnaire_versions where id=copied)<>'draft' then raise exception 'Not editable draft'; end if;
 begin perform public.change_questionnaire_status(vid,4,'distributed',null,'published',gen_random_uuid()); raise exception 'Distributed downgraded'; exception when object_not_in_prerequisite_state then null; end;
 perform public.change_questionnaire_status(vid,4,'distributed',null,'archived',gen_random_uuid());
 select archived_at into ar from public.questionnaires where id=(doc->>'questionnaireId')::uuid;
 if (select p.archived_at from public.questionnaires p join public.questionnaire_versions v on v.questionnaire_id=p.id where v.id=copied) is not null then raise exception 'Copy archived with source'; end if;
 perform public.change_questionnaire_status(vid,4,'distributed',ar,'distributed',gen_random_uuid());
 if (select to_jsonb(v) from public.questionnaire_versions v where id=vid)<>original then raise exception 'Restore changed distributed'; end if;
 perform set_config('request.jwt.claim.sub',consultant_id::text,true);
 if not exists(select 1 from public.questionnaire_responses where version_id=vid) then raise exception 'Responses lost'; end if;
 if not exists(select 1 from public.questionnaire_answers where version_id=vid and body='보존할 답변') then raise exception 'Answers lost'; end if;
 if exists(select 1 from public.questionnaire_versions where id=copied) then raise exception 'Draft leaked'; end if;
 begin perform 1 from private.questionnaire_status_requests; raise exception 'Receipts leaked'; exception when insufficient_privilege then null; end;

 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 question_doc:=jsonb_build_object('id',gen_random_uuid(),'title','원본','prompt','배치 질문','fields',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'label','답변','kind','text')),'rowMode','single');
 perform public.save_question(question_doc,0,gen_random_uuid());
 doc:=jsonb_build_object('questionnaireId',gen_random_uuid(),'versionId',gen_random_uuid(),'title','배치 질문지','sections',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'title','섹션','questions',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'logicalKey',gen_random_uuid(),'sourceQuestionId',question_doc->'id','text','배치 질문','details','[]'::jsonb)))));
 vid:=(doc->>'versionId')::uuid;
 perform public.save_questionnaire_draft(doc,0,gen_random_uuid());
 begin perform public.change_questionnaire_status(vid,1,'draft',null,'distributed',gen_random_uuid()); raise exception 'Placement distributed'; exception when object_not_in_prerequisite_state then null; end;
 if (select status from public.questionnaire_versions where id=vid)<>'draft' or (select revision from public.questionnaire_versions where id=vid)<>1 then raise exception 'Failed distribution partially committed'; end if;
 perform public.change_questionnaire_status(vid,1,'draft',null,'archived',gen_random_uuid());
 select archived_at into ar from public.questionnaires where id=(doc->>'questionnaireId')::uuid;
 perform public.archive_question((question_doc->>'id')::uuid,1);
 begin perform public.change_questionnaire_status(vid,1,'draft',ar,'draft',gen_random_uuid()); raise exception 'Archived source restored'; exception when invalid_parameter_value then null; end;
 if (select archived_at from public.questionnaires where id=(doc->>'questionnaireId')::uuid) is null then raise exception 'Failed restore partially committed'; end if;
end $$;
reset role;
rollback;
