begin;
create temporary table workflow_users(id uuid, role text);
insert into workflow_users select gen_random_uuid(),role from unnest(array['student','consultant','consultant_lead','admin','reviewer_lead']) role;
insert into auth.users(id) select id from workflow_users;
insert into public.profiles(id,role,name,student_period)
select id,case when role='reviewer_lead' then 'consultant_lead' else role end,'검증 '||role,case when role='student' then '1학년 1학기' end from workflow_users;
create temporary table workflow_data(doc jsonb);
insert into workflow_data values(jsonb_build_object('questionnaireId',gen_random_uuid(),'versionId',gen_random_uuid(),'title','워크플로 검증','sections',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'title','섹션','questions',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'logicalKey',gen_random_uuid(),'text','질문','details',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'title','비공개 의도','text','비공개 설명','visibleToConsultants',false),jsonb_build_object('id',gen_random_uuid(),'title','공개 의도','text','공개 설명','visibleToConsultants',true))))))));
grant select on workflow_users,workflow_data to authenticated;
set local role authenticated;
do $$
declare doc jsonb; vid uuid; qid uuid; owner_id uuid; person uuid; other uuid; a jsonb; result jsonb; aid uuid; save_id uuid;
begin
 select d.doc into doc from workflow_data d; vid:=(doc->>'versionId')::uuid; qid:=(doc#>>'{sections,0,questions,0,id}')::uuid;
 select id into owner_id from workflow_users where role='consultant_lead';
 select id into person from workflow_users where role='consultant';
 select id into other from workflow_users where role='admin';
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.save_questionnaire_draft(doc,0,gen_random_uuid());
 perform public.publish_questionnaire(vid,1);
 perform set_config('request.jwt.claim.sub',person::text,true);
 begin perform public.open_questionnaire_response(vid);raise exception 'Opened unpublished';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.distribute_questionnaire(vid,1);
 perform set_config('request.jwt.claim.sub',other::text,true);
 begin perform public.request_questionnaire_review(gen_random_uuid(),vid,qid,'late review');raise exception 'Reviewed distributed';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',person::text,true);
 if not exists(select 1 from public.unread_distributed_questionnaires() where version_id=vid) then raise exception 'Missing NEW';end if;
 perform public.open_questionnaire_response(vid);perform public.open_questionnaire_response(vid);
 if exists(select 1 from public.unread_distributed_questionnaires() where version_id=vid) then raise exception 'Still NEW';end if;
 a:=jsonb_build_object(qid::text,'first');save_id:=gen_random_uuid();
 result:=public.save_questionnaire_response(vid,a,0,save_id,false);
 if (result->>'revision')::int<>1 then raise exception 'revision';end if;
 perform public.save_questionnaire_response(vid,a,0,save_id,false);
 select id into aid from public.questionnaire_answers where question_id=qid;
 begin perform public.save_questionnaire_response(vid,a,0,gen_random_uuid(),false);raise exception 'No conflict';exception when serialization_failure then null;end;
 begin perform public.save_questionnaire_response(vid,jsonb_build_object(qid::text,''),1,gen_random_uuid(),true);raise exception 'Empty complete';exception when invalid_parameter_value then null;end;
 a:=jsonb_build_object(qid::text,'final');save_id:=gen_random_uuid();
 perform public.save_questionnaire_response(vid,a,1,save_id,true);
 perform public.save_questionnaire_response(vid,a,1,save_id,true);
 if not exists(select 1 from public.questionnaire_answers where id=aid and body='final') then raise exception 'Answer ID changed';end if;
 begin perform public.save_questionnaire_response(vid,a,2,gen_random_uuid(),false);raise exception 'Edited complete';exception when object_not_in_prerequisite_state then null;end;
 begin update public.questionnaire_answers set body='bypass' where id=aid;raise exception 'Direct write allowed';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',other::text,true);
 if exists(select 1 from public.questionnaire_answers where id=aid) then raise exception 'Other answer leaked';end if;
 perform set_config('request.jwt.claim.sub',(select id::text from workflow_users where role='student'),true);
 begin perform public.save_questionnaire_response(vid,a,0,gen_random_uuid(),false);raise exception 'Student write';exception when insufficient_privilege then null;end;
end $$;
reset role;
select 'Answer save, IDs, completion, permissions and NEW checks passed' as result;
rollback;
