import type { ConfirmedCurriculum } from '../_lib/curriculum';

// Snapshot of the confirmed curriculum, not a verified replacement for the school source.
export default {
  schoolName: '흑석고등학교',
  currentGrade: 1,
  targetCohort: 2026,
  track: '일반 과정',
  source: 'schoolinfo',
  linkedRules: [
    '1학년 ‘음악’과 ‘미술’은 1, 2학기 교차 이수',
    '2, 3학년 선택 과목 중 기술·가정/정보, 제2외국어/한문, 교양 교과(군)에서 14학점 이상 이수해야 함',
    '2, 3학년 선택 과목 중 예술 교과(군)에서 4학점 이상 이수해야 함',
    '학교 지정이 아닌 2, 3학년 국어, 영어, 수학 교과(군) 과목 선택 시 24학점 이내로 선택해야 함',
  ],
  priorRequiredCourses: [
    {
      id: 'grade-1-import-required-1',
      name: '공통국어1',
      credit: 3,
      domain: '국어',
      description: null,
    },
    {
      id: 'grade-1-import-required-2',
      name: '공통국어2',
      credit: 4,
      domain: '국어',
      description: null,
    },
    {
      id: 'grade-1-import-required-3',
      name: '공통수학1',
      credit: 4,
      domain: '수학',
      description: null,
    },
    {
      id: 'grade-1-import-required-4',
      name: '공통수학2',
      credit: 4,
      domain: '수학',
      description: null,
    },
    {
      id: 'grade-1-import-required-5',
      name: '공통영어1',
      credit: 4,
      domain: '영어',
      description: null,
    },
    {
      id: 'grade-1-import-required-6',
      name: '공통영어2',
      credit: 3,
      domain: '영어',
      description: null,
    },
    {
      id: 'grade-1-import-required-7',
      name: '한국사1',
      credit: 3,
      domain: '사회(역사/도덕포함)',
      description: null,
    },
    {
      id: 'grade-1-import-required-8',
      name: '한국사2',
      credit: 3,
      domain: '사회(역사/도덕포함)',
      description: null,
    },
    {
      id: 'grade-1-import-required-9',
      name: '통합사회1',
      credit: 4,
      domain: '사회(역사/도덕포함)',
      description: null,
    },
    {
      id: 'grade-1-import-required-10',
      name: '통합사회2',
      credit: 4,
      domain: '사회(역사/도덕포함)',
      description: null,
    },
    {
      id: 'grade-1-import-required-11',
      name: '통합과학1',
      credit: 4,
      domain: '과학',
      description: null,
    },
    {
      id: 'grade-1-import-required-12',
      name: '통합과학2',
      credit: 4,
      domain: '과학',
      description: null,
    },
    {
      id: 'grade-1-import-required-13',
      name: '과학탐구실험1',
      credit: 1,
      domain: '과학',
      description: null,
    },
    {
      id: 'grade-1-import-required-14',
      name: '과학탐구실험2',
      credit: 1,
      domain: '과학',
      description: null,
    },
    {
      id: 'grade-1-import-required-15',
      name: '체육1',
      credit: 2,
      domain: '체육',
      description: null,
    },
    {
      id: 'grade-1-import-required-16',
      name: '체육2',
      credit: 2,
      domain: '체육',
      description: null,
    },
    {
      id: 'grade-1-import-required-17',
      name: '음악',
      credit: 3,
      domain: '예술',
      description: null,
    },
    {
      id: 'grade-1-import-required-18',
      name: '음악',
      credit: 3,
      domain: '예술',
      description: null,
    },
    {
      id: 'grade-1-import-required-19',
      name: '미술',
      credit: 3,
      domain: '예술',
      description: null,
    },
    {
      id: 'grade-1-import-required-20',
      name: '미술',
      credit: 3,
      domain: '예술',
      description: null,
    },
    {
      id: 'grade-1-import-required-21',
      name: '정보와 디지털 문해력',
      credit: 1,
      domain: '교양',
      description: null,
    },
    {
      id: 'grade-1-import-required-22',
      name: '생성형AI와 메이커 실습',
      credit: 1,
      domain: '교양',
      description: null,
    },
  ],
  terms: [
    {
      id: 'grade-2-semester-1',
      label: '2-1',
      requiredCourses: [
        {
          id: 'grade-2-semester-1-import-required-1',
          name: '문학',
          credit: 4,
          domain: '국어',
          description: null,
        },
        {
          id: 'grade-2-semester-1-import-required-2',
          name: '대수',
          credit: 4,
          domain: '수학',
          description: null,
        },
        {
          id: 'grade-2-semester-1-import-required-3',
          name: '영어Ⅰ',
          credit: 4,
          domain: '영어',
          description: null,
        },
        {
          id: 'grade-2-semester-1-import-required-4',
          name: '스포츠 생활1',
          credit: 2,
          domain: '체육',
          description: null,
        },
      ],
      selectionGroups: [
        {
          id: 'grade-2-semester-1-import-group-1',
          name: '2학년 1학기 선택 15학점(택5)',
          choose: 5,
          rule: '15(택5)',
          courses: [
            {
              id: 'grade-2-semester-1-import-group-1-course-1',
              name: '주제 탐구 독서',
              credit: 3,
              domain: '국어',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-2',
              name: '기하',
              credit: 3,
              domain: '수학',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-3',
              name: '미디어 영어',
              credit: 3,
              domain: '영어',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-4',
              name: '세계시민과 지리',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-5',
              name: '세계사',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-6',
              name: '사회와 문화',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-7',
              name: '현대사회와 윤리',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-8',
              name: '물리학',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-9',
              name: '화학',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-10',
              name: '생명과학',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-11',
              name: '지구과학',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-12',
              name: '정보',
              credit: 3,
              domain: '기술·가정/정보',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-13',
              name: '중국어',
              credit: 3,
              domain: '제2외국어/한문',
              description: null,
            },
            {
              id: 'grade-2-semester-1-import-group-1-course-14',
              name: '일본어',
              credit: 3,
              domain: '제2외국어/한문',
              description: null,
            },
          ],
        },
      ],
    },
    {
      id: 'grade-2-semester-2',
      label: '2-2',
      requiredCourses: [
        {
          id: 'grade-2-semester-2-import-required-1',
          name: '독서와 작문',
          credit: 4,
          domain: '국어',
          description: null,
        },
        {
          id: 'grade-2-semester-2-import-required-2',
          name: '미적분Ⅰ',
          credit: 4,
          domain: '수학',
          description: null,
        },
        {
          id: 'grade-2-semester-2-import-required-3',
          name: '영어Ⅱ',
          credit: 4,
          domain: '영어',
          description: null,
        },
        {
          id: 'grade-2-semester-2-import-required-4',
          name: '스포츠 생활2',
          credit: 2,
          domain: '체육',
          description: null,
        },
      ],
      selectionGroups: [
        {
          id: 'grade-2-semester-2-import-group-1',
          name: '2학년 2학기 선택 15학점(택5)',
          choose: 5,
          rule: '15(택5)',
          courses: [
            {
              id: 'grade-2-semester-2-import-group-1-course-1',
              name: '독서 토론과 글쓰기',
              credit: 3,
              domain: '국어',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-2',
              name: '인공지능 수학',
              credit: 3,
              domain: '수학',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-3',
              name: '영미 문학 읽기',
              credit: 3,
              domain: '영어',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-4',
              name: '한국지리 탐구',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-5',
              name: '동아시아 역사 기행',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-6',
              name: '법과 사회',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-7',
              name: '윤리와 사상',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-8',
              name: '역학과 에너지',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-9',
              name: '물질과 에너지',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-10',
              name: '세포와 물질대사',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-11',
              name: '지구시스템과학',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-12',
              name: '인공지능 기초',
              credit: 3,
              domain: '기술·가정/정보',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-13',
              name: '일본어 회화',
              credit: 3,
              domain: '제2외국어/한문',
              description: null,
            },
            {
              id: 'grade-2-semester-2-import-group-1-course-14',
              name: '중국어 회화',
              credit: 3,
              domain: '제2외국어/한문',
              description: null,
            },
          ],
        },
      ],
    },
    {
      id: 'grade-3-semester-1',
      label: '3-1',
      requiredCourses: [
        {
          id: 'grade-3-semester-1-import-required-1',
          name: '화법과 언어',
          credit: 4,
          domain: '국어',
          description: null,
        },
        {
          id: 'grade-3-semester-1-import-required-2',
          name: '확률과 통계',
          credit: 4,
          domain: '수학',
          description: null,
        },
        {
          id: 'grade-3-semester-1-import-required-3',
          name: '영어 독해와 작문',
          credit: 3,
          domain: '영어',
          description: null,
        },
        {
          id: 'grade-3-semester-1-import-required-4',
          name: '스포츠 문화',
          credit: 2,
          domain: '체육',
          description: null,
        },
      ],
      selectionGroups: [
        {
          id: 'grade-3-semester-1-import-group-1',
          name: '3학년 1학기 선택 12학점(택4)',
          choose: 4,
          rule: '12(택4)',
          courses: [
            {
              id: 'grade-3-semester-1-import-group-1-course-1',
              name: '언어생활 탐구',
              credit: 3,
              domain: '국어',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-2',
              name: '미적분Ⅱ',
              credit: 3,
              domain: '수학',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-3',
              name: '경제 수학',
              credit: 3,
              domain: '수학',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-4',
              name: '심화 영어',
              credit: 3,
              domain: '영어',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-5',
              name: '경제',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-6',
              name: '정치',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-7',
              name: '인문학과 윤리',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-8',
              name: '도시의 미래 탐구',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-9',
              name: '사회문제 탐구',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-10',
              name: '윤리문제 탐구',
              credit: 3,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-11',
              name: '전자기와 양자',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-12',
              name: '화학 반응의 세계',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-13',
              name: '생물의 유전',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-14',
              name: '행성우주과학',
              credit: 3,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-1-course-15',
              name: '정보과학',
              credit: 3,
              domain: '기술·가정/정보',
              description: null,
            },
          ],
        },
        {
          id: 'grade-3-semester-1-import-group-2',
          name: '3학년 1학기 선택 4학점(택2)',
          choose: 2,
          rule: '4(택2)',
          courses: [
            {
              id: 'grade-3-semester-1-import-group-2-course-1',
              name: '음악 연주와 창작',
              credit: 2,
              domain: '예술',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-2-course-2',
              name: '미술 창작',
              credit: 2,
              domain: '예술',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-2-course-3',
              name: '교육의 이해',
              credit: 2,
              domain: '교양',
              description: null,
            },
            {
              id: 'grade-3-semester-1-import-group-2-course-4',
              name: '인간과 경제활동',
              credit: 2,
              domain: '교양',
              description: null,
            },
          ],
        },
      ],
    },
    {
      id: 'grade-3-semester-2',
      label: '3-2',
      requiredCourses: [
        {
          id: 'grade-3-semester-2-import-required-1',
          name: '스포츠 과학',
          credit: 1,
          domain: '체육',
          description: null,
        },
      ],
      selectionGroups: [
        {
          id: 'grade-3-semester-2-import-group-1',
          name: '3학년 2학기 선택 20학점(택5)',
          choose: 5,
          rule: '20(택5)',
          courses: [
            {
              id: 'grade-3-semester-2-import-group-1-course-1',
              name: '문학과 영상',
              credit: 4,
              domain: '국어',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-2',
              name: '매체 의사소통',
              credit: 4,
              domain: '국어',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-3',
              name: '인공지능을 위한 선형대수학',
              credit: 4,
              domain: '수학',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-4',
              name: '실용통계',
              credit: 4,
              domain: '수학',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-5',
              name: '수학과 문화',
              credit: 4,
              domain: '수학',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-6',
              name: '심화 영어 독해와 작문',
              credit: 4,
              domain: '영어',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-7',
              name: '세계 문화와 영어',
              credit: 4,
              domain: '영어',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-8',
              name: '여행지리',
              credit: 4,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-9',
              name: '역사로 탐구하는 현대 세계',
              credit: 4,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-10',
              name: '기후변화와 지속가능한 세계',
              credit: 4,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-11',
              name: '금융과 경제생활',
              credit: 4,
              domain: '사회(역사/도덕포함)',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-12',
              name: '고급 물리학',
              credit: 4,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-13',
              name: '과학의 역사와 문화',
              credit: 4,
              domain: '과학',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-1-course-14',
              name: '기후변화와 환경생태',
              credit: 4,
              domain: '과학',
              description: null,
            },
          ],
        },
        {
          id: 'grade-3-semester-2-import-group-2',
          name: '3학년 2학기 선택 8학점(택4)',
          choose: 4,
          rule: '8(택4)',
          courses: [
            {
              id: 'grade-3-semester-2-import-group-2-course-1',
              name: '진로와 직업',
              credit: 2,
              domain: '교양',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-2-course-2',
              name: '인간과 철학',
              credit: 2,
              domain: '교양',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-2-course-3',
              name: '논리와 사고',
              credit: 2,
              domain: '교양',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-2-course-4',
              name: '인간과 심리',
              credit: 2,
              domain: '교양',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-2-course-5',
              name: '논술',
              credit: 2,
              domain: '교양',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-2-course-6',
              name: '머신러닝 기반 융합 탐구 실습',
              credit: 2,
              domain: '교양',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-2-course-7',
              name: '음악 감상과 비평',
              credit: 2,
              domain: '예술',
              description: null,
            },
            {
              id: 'grade-3-semester-2-import-group-2-course-8',
              name: '미술 감상과 비평',
              credit: 2,
              domain: '예술',
              description: null,
            },
          ],
        },
      ],
    },
  ],
} satisfies ConfirmedCurriculum;
